#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

xset +fp /usr/share/fonts/local
xset fp rehash
wmname LG3D

xsetroot -cursor_name left_ptr
if [[ $(hostname) == leo ]]; then
    hsetroot -fill '/home/ethan/usr/pictures/Wallpapers/templeFall.png'
else
    hsetroot -fill '/home/ethan/usr/pictures/grey_wash_wall/grey_wash_wall.png'
fi

case $WM in
		openbox			)exec openbox-session;;
		bspwm			)exec sxhkd -c "/home/ethan/etc/bspwm/sxhkd/sxhkdrc" &
                         exec bspwm -c "/home/ethan/etc/bspwm/bspwm/bspwmrc";;
		xmonad			)exec dbus-launch xmonad;;
		herbstluftwm    )exec herbstluftwm;;
    	2bwm            )2bwm & exec urxvt;;
		awesome			)exec awesome;;
		dwm 			)exec dwm;;
		*			    )exec sxhkd -c "/home/ethan/etc/bspwm/sxhkdrc" -f 100 &
                         exec bspwm -c "/home/ethan/etc/bspwm/bspwmrc";;
esac

#/home/ethan/bin/startdwm &
