#!/bin/sh

bspc config border_width        0
bspc config top_padding         15
bspc config bottom_padding      15
bspc config left_padding        15
bspc config right_padding       15
bspc config window_gap          13

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Visual options
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config normal_border_color     "#242020"
bspc config active_border_color     "#242020"
bspc config focused_border_color    "#C1BEBE"
bspc config presel_feedback_color   "#FFFFFF"
bspc config urgent_border_color     "#d9534f"
bspc config ignore_ewmh_focus       false
bspc config focus_by_distance       true

# Rules
bspc rule -a '*' state=floating
bspc rule -a Conky sticky=on manage=off layer=below
bspc rule -a lemonbar layer=below
bspc rule -a astime sticky=on
bspc rule -a feh sate=floating manage=on
bspc rule -a sun-awt-X11-XFramePeer state=floating manage=on
bspc rule -a Steam state=floating desktop=^5 follow=off
bspc rule -a google-chrome desktop=^1 follow=off
