#!/bin/bash

bspc config border_width        1
bspc config window_gap          20

i=0
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d {1,2,3,4,5,6,7,8,9,10}
    let i++
done
NMON=$i
unset i

#bspc config top_padding 25

# Visual options
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config normal_border_color     "#242020"
bspc config active_border_color     "#242020"
bspc config focused_border_color    "#C1BEBE"
bspc config presel_border_color     "#FFFFFF"
bspc config urgent_border_color     "#d9534f"
bspc config ignore_ewmh_focus       false
bspc config focus_by_distance       true


# Rules
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a feh floating=on manage=on
bspc rule -a sun-awt-X11-XFramePeer floating=on manage=on
bspc rule -a Steam floating=true desktop=^5 follow=off
bspc rule -a google-chrome desktop=^1 follow=off
