#!/bin/env bash

panel_group_wid=$(xdo id -a bar | head -1)
panel_bar_wid=$(xdo id -a bar | tail -1)

bspc subscribe node_state | while read event moniter desktop wid state toggle; do
    [ $state = "fullscreen" -a $toggle = "on" ] && xdo below -t $wid $panel_bar_wid && xdo below -t $wid $panel_group_wid
done
