#! /bin/env bash
# configuration variables
refresh_rate=0              # how often will the bar update

COLOR_INACTIVE="#ff191919"
COLOR_ACTIVE="#FFFFFFFF"
COLOR_OCCUPIED="#ff4c4c4c"
COLOR_URGENT="#ffFF0000"
COLOR_SPACE="#ff121010"

BLOCK="█"
SPACE=" "
WORKSPACES=10
BLOCK_SIZE=12 #How many pixels does BLOCK take?

# calculates how many blocks per bar
display_width="$(xrandr | grep '*')"
display_width="$(echo "${display_width%%x*}" | sed 's/^ *//')"
block_width="$(echo "$display_width/($BLOCK_SIZE*$WORKSPACES)" | bc)"

# determine bar and space ratio based on width
#bar_width="$(echo "$block_width * 0.99" | bc)"
#space_width="$(echo "$block_width * 0.01" | bc)"

# rounds down to nearest integer
#bar_width="$(printf '%.*f' 0 $bar_width)"
#space_width="$(printf '%.*f' 0 $space_width)"

#if [ $space_width -lt 1 ]; then
#    space_width=1
#fi

# builds the BAR
for ((i=0; i<$block_width; i++)); do
	BAR+="$BLOCK"
done

# builds the SPACE between BARs
#for ((i=0; i<$space_width; i++)); do
#	SPACE+="$SPACE"
#done

# This loop will fill a buffer with our infos, and output it to stdout.
FIFO="$HOME/var/PANEL_FIFO"
[ -e "$FIFO" ] && rm "$FIFO"
mkfifo "$FIFO"

# sends status of workspaces to named pipe
bspc subscribe report > "$FIFO" &

# colors the bar based on whether the space is active
cat "$FIFO" | while read -r line ; do
    wm_infos=''
    IFS=':'
    set -- ${line#?}
    while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
            [OFU]*)
                # active desktop
                wm_infos="$wm_infos%{B$COLOR_ACTIVE}%{F$COLOR_ACTIVE}$BAR%{B$COLOR_SPACE}$SPACE"
                ;;
            o*)
                # inactive but occupied desktop
                wm_infos="$wm_infos%{B$COLOR_OCCUPIED}%{F$COLOR_OCCUPIED}$BAR%{B$COLOR_SPACE}$SPACE"
                ;;
            f*)
                # inactive desktop
                wm_infos="$wm_infos%{B$COLOR_INACTIVE}%{F$COLOR_INACTIVE}$BAR%{B$COLOR_SPACE}$SPACE"
                ;;
            u*)
                # urgent desktop
                wm_infos="$wm_infos%{B$COLOR_URGENT}%{F$COLOR_URGENT}$BAR%{B$COLOR_SPACE}$SPACE"
                ;;
	    m*)
		break
		;;
        esac
    shift
    done

    echo $wm_infos
    wm_infos=''

    sleep ${refresh_rate}
done
