#!/usr/bin/env bash

EDGE_GAP=0
barbg='#ff121010'

width="$(xrandr | grep '*')"
width="$(echo "${width%%x*}" | sed 's/^ *//')"

barWidth="$(echo $width - $EDGE_GAP - $EDGE_GAP | bc )"

$HOME/etc/panel/mkbar | lemonbar -p -B "$barbg" -g "$barWidth"x18+$EDGE_GAP+2 -f "xft:Inconsolata:style=Semibold:pixelsize=11:antialias=true:hinting=slight" -f "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" &

$HOME/etc/panel/mkgroup | lemonbar -p -B "$barbg" -g "$barWidth"x2+$EDGE_GAP+0 -f "xft:unifont:style=Medium:antialias=false:dpi=96" &

sleep 4;
